### ISSUE TITLE
waitra-0.0.3.0 test suite failure

### ISSUE THREAD

**Issue by peti** [futurice/waitra#4]
Citing from http://hydra.cryp.to/build/899793/log/raw:

```
running tests
Running 1 test suites...
Test suite test: RUNNING...
Unit tests
  echo case 1: OK
  echo case 2: OK
  json case 1: OK
  json case 2: FAIL
    Exception: WaiTestFailure "Expected status code 400, but received 404"

1 out of 4 tests failed (0.00s)
Test suite test: FAIL
```

**Comment by phadej** [comment]
Hmm, it fails on travis with GHC 7.6 and 7.10 https://travis-ci.org/futurice/waitra/builds/64433562 (7.8 pending atm). My local 7.8 setup got cabal.hell, but when installed dependencies from stackage nightly, tests are ok.

Interesting, I'll investigate this over weekend.

**Comment by bergmark** [comment]
Bump, test suite failed on stackage, I've disabled it for now.

**Comment by phadej** [comment]
Ah, it took some time to realise what happens. That because `42` is valid json in aeson-0.9 but not aeson-0.8. Fixed version will be soon on Hackage.

**Comment by phadej** [comment]
ping @bergmark , `waitra-0.0.4.0` uploaded to Hackage

**Comment by bergmark** [comment]
ping @danburton

**Comment by DanBurton** [comment]
Re-enabled the test suite on stackage.
